# Generated by Django 5.1.1 on 2024-09-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('data_de_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=155)),
            ],
        ),
    ]
